# Generated by Django 4.1.6 on 2023-02-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_checkout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.FileField(upload_to="images/"),
        ),
    ]
